### ISSUE TITLE
Links to demos are not working

### ISSUE THREAD

**Issue by CarlMungazi** [richardcrng/redux-leaves#148]
On the docs website, all the links which reference the "30 second demo" are broken. I am not sure what they are supposed to be pointing to? The "demo" button on the main page works and links to this: https://runkit.com/richardcrng/redux-leaves-playground.

Happy to do a PR if you can tell me where you want these links to point.

**Comment by richardcrng** [comment]
Thanks for flagging @CarlMungazi! Can you link the specific pages which have broken links?

I think I probably intended them to direct to the internal page [Basic Example](https://redux-leaves.js.org/docs/examples/basic-example).

**Comment by CarlMungazi** [comment]
The broken links can be found at: 
- https://redux-leaves.js.org/docs/redux-leaves
- https://redux-leaves.js.org/docs/api/bundle

**Comment by richardcrng** [comment]
Merged in #149 - thanks for the work!
